### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xf78** [Bioconductor/BiocParallel#105]
Hi,i want to install SingleR package,so i install newest BioParallel in windows R(3.6.1) as follow:
BiocManager::install("BiocParallel")

but I encountered an installation error,as follow:

c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o BiocParallel.dll tmp.def ipcmutex.o -LC:/PROGRA~1/R/R-36~1.1/bin/x64 -lR
installing to C:/Users/96183/Documents/R/win-library/3.6/00LOCK-BiocParallel/00new/BiocParallel/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
错误: objects 'mcparallel', 'mccollect' are not exported by 'namespace:parallel'
停止执行
ERROR: lazy loading failed for package 'BiocParallel'

i think objects 'mcparallel', 'mccollect' maybe implement in linux system,so how could i solve this error,thanks.

**Comment by mtmorgan** [comment]
Thank you, this is a bug in BiocParallel. It has been fixed, and should be available when version 1.19.4 becomes available, in approximately 48 hours.
