### ISSUE TITLE
Conflicts while using MulticoreParam with RSQLite/DBI

### ISSUE THREAD

**Issue by plantton** [Bioconductor/BiocParallel#129]
I believe this issue is related to MulticoreParam parameter in `bplapply`.  

Example:  

Generate random data:
```R
df1 <- data.frame(replicate(10,sample(1:10,1000,rep=TRUE)))
f <- rep(c(TRUE, FALSE), 500)
```

Case 1: Use bplapply with `SerialParam`:  
```R
sql_parallel1  <-   bplapply(split(df1, f = f), function(z) {
                                con <- dbConnect(SQLite(), tempfile(fileext = ".db"))
                                dbWriteTable(con, "tbl", z)
                                con
                              }, BPPARAM = SerialParam())
```

The returning result is correct:
```R
> sql_parallel1[1]
$`FALSE`
<SQLiteConnection>
  Path: /pathtoTempdir/file58f54286840.db
  Extensions: TRUE
```

Case 2: Use bplapply with `MulticoreParam`:  
```R
sql_parallel2  <-   bplapply(split(df1, f = f), function(z) {
                                con <- dbConnect(SQLite(), tempfile(fileext = ".db"))
                                dbWriteTable(con, "tbl", z)
                                con
                             }, BPPARAM = MulticoreParam())
```

The resulting list has length 2. But the `dbConnection` instances in the list are all disconnected.

```R
> sql_parallel2[1]
$`FALSE`
<SQLiteConnection>
  DISCONNECTED

>  sql_parallel2[2]
$`TRUE`
<SQLiteConnection>
  DISCONNECTED
```

I checked the SQLite db-files in my `tempdir()`. The dbfiles are actually created, but only disconnected afterwards. How can I keep them alive/open, just like using `SerialParam` in the function?

```R
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] RSQLite_2.2.1       msdata_0.30.0       MsBackendSql_0.5.1 
[4] Spectra_1.0.3       ProtGenerics_1.22.0 BiocParallel_1.24.1
[7] S4Vectors_0.28.0    BiocGenerics_0.36.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        MsCoreUtils_1.2.0 MASS_7.3-53       IRanges_2.24.0   
 [5] bit_4.0.4         rlang_0.4.8       blob_1.2.1        tools_4.0.0      
 [9] Biobase_2.50.0    DBI_1.1.0         mzR_2.24.1        bit64_4.0.5      
[13] digest_0.6.27     vctrs_0.3.5       fs_1.5.0          codetools_0.2-18 
[17] ncdf4_1.17        memoise_1.1.0     compiler_4.0.0    pkgconfig_2.0.3
```

**Comment by mtmorgan** [comment]
A more extreme, and probably more understandable, example is to use SnowParam -- your 'workers' are on separate processes, maybe even separate machines, and the SQL connections to a local database created on one process cannot be known by the other processes on other machines. In a little more detail, the connection involves C-level data structures, and the C-level data structures are not shared between the manager and worker. Its not something that BiocParallel could solve (the upstream RSQLite package could use C-level memory for the database shared by the different processes, but this wouldn't address the different machine scenario, would be very difficult to implement robustly, and is not BiocParallel's problem!).

A similar problem occurs in the other direction, where a database connection is created on the manager but passed to the workers.

The workaround for the single-machine case is to pass the file path to the database between manager and worker.
