### ISSUE TITLE
BiocParallel Error Occurring when used in biology-focused package

### ISSUE THREAD

**Issue by compbiolover** [Bioconductor/BiocParallel#135]
Hi all,
I am currently a computational biologist who uses a package to analyze some data that uses BiocParallel for their multi-core code, and I am getting a hard to interpret error. I have had no previous exposure to BiocParallel, so I was curious to get some direction on what this error message is trying to say to better communicate with the package maintainer of the biology-focused package. Thanks so much!
"Error: BiocParallel errors
element index: 1, 2, 3, 4, 5, 6, ...
first error: object '382.017' of mode 'function' was not found"

**Comment by vjcitn** [comment]
Thanks for posting.  I'd make two suggestions.  First, have a look at the posting guide https://bioconductor.org/help/support/posting-guide/ ... It tells how to prepare comments and questions to 
help developers, and other folks who can advise, get you the information you need to go forward.
Second, use support.bioconductor.org ... someone may have triggered a similar error and has a solution.
For me, the error you report is very exotic and suggests a pretty basic error of syntax but without a lot
more information it will be impossible to give good advice.

**Comment by compbiolover** [comment]
@vjcitn Thanks for the fast reply. This issue can be closed as I have not correctly formatted it. I will check out the resources you suggest and only open a new, adequately formatted issue if I cannot find my answer from them. Apologies for not accurately formatting this post.

**Comment by mtmorgan** [comment]
Usually a good first step is to run your code in parallel; the package might / should respect

```
BiocParallel::register(SerialParam())
```
and then the code will run sequentially, and you can use standard R debugging tools like `traceback()` (the outptu of `traceback()` would be helpful for other to help debug) or `options(error=recover)` and `debug()` to figure out what is going on.

You can generate the error if you imagine code like
```
> lapply(1:2, "382.017")
Error in get(as.character(FUN), mode = "function", envir = envir) :
  object '382.017' of mode 'function' was not found
```
which suggests that, either in your own code or in the package code, arguments have somehow been mis-aligned.

For more advanced investigation of errors, use `browseVignettes("BiocParallel")` and visit the "Errors, Logs and Debugging" vignette.

**Comment by compbiolover** [comment]
@mtmorgan Thanks for your suggestion. It helped me solve my problem. This issue can be closed.
