### ISSUE TITLE
`bpstart()` hangs on laptop with Intel i7 4 core CPU

### ISSUE THREAD

**Issue by breidan** [Bioconductor/BiocParallel#136]
Dear all,
I am trying to process 21 GB of MS data with `xcms` but do not get anywhere. I believe the problem is that the SnowParam back-end cannot start. Whenever I try

> `register(bpstart(SnowParam(4)))`

R freezes. Yet with 

> `register(bpstart(SerialParam()))`

everything is fine and `xcms` runs through albeit too slow. Anyone has a suggestion on this?

I am working with WIN10, R4.0.3, and Bioconductor 3.12.

**Comment by mtmorgan** [comment]
BiocParallel (and the base R parallel package) uses socket 'ports' to communicate between manager and worker, and likely the port is blocked on your computer, maybe by a system administration policy. One you find an open port, it can be specified via the argument `manager.port=` to `SnowParam()`.

I'm not really sure how to identify open ports on your machine; I googled for "windows port open check" and two hits on 'howtogeek' and stackoverflow seemed promising.

**Comment by breidan** [comment]
@mtmorgan ,
thanks for the tip but unfortunately it does not make a difference. I tried a number of different ports which were supposedly open in different number ranges to avoid using a blocked range and always `register`ing it would hang up. I have inquired with our ICT people to see if there are blocked ranges for our corporate laptops.

**Comment by HenrikBengtsson** [comment]
@mtmorgan is correct here; it's most likely your Windows 10 firewall that prevents R from opening a port.  When setting up PSOCK parallel workers (aka "snow" workers) on n a non-locked down Windows machine, Windows will typically pop up a firewall dialog asking you to add the port to the acceptance list (which I think requires you have admin rights on the machine).

An alternative to using PSOCK parallel workers is to use the [**callr**](https://cran.r-project.org/package=callr) package to run parallel workers. It does not rely on socket connections and therefore also does not run into firewall problems.  To use **callr** as a parallel backend for **BiocParallel**, use `DoparParam()` in combination of [**future**](https://cran.r-project.org/package=future) framework as follows:

```r
library(BiocParallel)

# 1. Tell BiocParallel to internally use foreach() %dopar% { ... }
register(DoparParam())

# 2. Tell foreach() %dopar% { ... } to use doFuture and the 'future' framework
doFuture::registerDoFuture()

# 3. Tell 'future' to use 'callr' as the parallel backend
future::plan(future.callr::callr, workers = 4)
```

You can see that this does indeed run in parallel by asking each parallel worker for its process identifier.  You should get four unique PIDs - one for each workers;

```r
> str(bplapply(1:10, FUN = function(x) Sys.getpid()))
List of 10
 $ : int 5116
 $ : int 5116
 $ : int 5116
 $ : int 5131
 $ : int 5131
 $ : int 5146
 $ : int 5146
 $ : int 5157
 $ : int 5157
 $ : int 5157
```

Comparing to sequential processing:

```r
> register(SerialParam())
> str(bplapply(1:10, FUN = function(x) Sys.getpid()))
List of 10
 $ : int 2569
 $ : int 2569
 $ : int 2569
 $ : int 2569
 $ : int 2569
 $ : int 2569
 $ : int 2569
 $ : int 2569
 $ : int 2569
 $ : int 2569
```

**Comment by breidan** [comment]
Dear @HenrikBengtsson,
thanks for the info. Very much appreciated.
I have to admit though when I tried again today with the same setup 

> `register(bpstart(SnowParam(4)))`

went trough without a glitch. Do not know what happened.
Any way, thanks for the help and a nice piece of software (@mtmorgan )
