### ISSUE TITLE
Error in serialize(data, node$con) : error writing to connection

### ISSUE THREAD

**Issue by yuan596** [Bioconductor/BiocParallel#143]
hello，I have a problem when use the BiocParallel package.When I use the bplappy() function，it reports an error and terminates the code operation：
Error in serialize(data, node$con) : 链结书写发生了错误
Calls: local ... .send -> <Anonymous> -> sendData.SOCKnode -> serialize
how can I solve this problem?
 Thank you ~

**Comment by mtmorgan** [comment]
This could be because the data (input or return) is too large. Pass less data, e.g., a path to a file on your system instead of the contents of the file in memory.

It could also be that an error occurs in your code. Try running with `register(SerialParam())` instead of in parallel.

Please report back here if this helps.

**Comment by yuan596** [comment]
hi,
I want to speed up code execution by using this package.But this error occurs frequently, and it resumes normal operation after a while. I don't know why.
thank you~






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Bioconductor/BiocParallel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月17日(星期四) 晚上10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Bioconductor/BiocParallel] Error in serialize(data, node$con) : error writing to connection (#143)





 
This could be because the data (input or return) is too large. Pass less data, e.g., a path to a file on your system instead of the contents of the file in memory.
 
It could also be that an error occurs in your code. Try running with register(SerialParam()) instead of in parallel.
 
Please report back here if this helps.

**Comment by mtmorgan** [comment]
Please see my previous comment, I cannot be more helpful without a reproducible example.
