### ISSUE TITLE
Idea for "bpforeach"

### ISSUE THREAD

**Issue by DarwinAwardWinner** [Bioconductor/BiocParallel#17]
So, I just thought a little about how to do a "bpforeach" implementation, and I think the simplest way to do it would be to implement a `%dobp%` operator that uses the registered BiocParallel param to parallelize the foreach iteration. Usage would be like the `%dopar%` operator:

    foreach(x=1:10) %dobp% { sqrt(x); }

**Comment by vobencha** [comment]
Are you interested in pursuing this or should I close this issue? Trying to clean up the open issues ...

**Comment by mtmorgan** [comment]
I like the conceptual simplicity of bplapply; it is functionally equivalent.

**Comment by vobencha** [comment]
Thanks. Closing this issue.
