### ISSUE TITLE
first error: NA/NaN/Inf in foreign function call (arg 1)

### ISSUE THREAD

**Issue by stefnoerman** [Bioconductor/BiocParallel#170]
HI,

I am running peakpicking in xcms and got an error message about BiocParallel. do you perhaps know what is happening and how ito solve it? 

Thank you

![image](https://user-images.githubusercontent.com/94456030/141987167-c1509b09-32b7-4496-b86e-d516c6bd5ffe.png)

**Comment by Jiefei-Wang** [comment]
Hi, it looks like this is a bug in your code. Have you tried `lapply` or `bplapply` with `SerialParam` to confirm where the issue is?

**Comment by mtmorgan** [comment]
If this is a problem with xcms, then report it to `packageDescription("xcms")$BugReports` or on the Bioconductor support site https://support.bioconductor.org.

**Comment by Jiefei-Wang** [comment]
Hi, if you really want to debug it(I think this should be a bug in xcms), you can use `bptry` to capture the error and then use `conditionCall` to examine the call stack. For example
```
> res <- bptry(bplapply(1:2, function(x)stop("Hi"), BPPARAM = SerialParam()))
> res
[[1]]
<remote_error in FUN(...): Hi>
traceback() available as 'attr(x, "traceback")'

[[2]]
<unevaluated_error: not evaluated due to previous error>
> conditionCall(res[[1]])
FUN(...)
```
In most cases, this should be enough for you to find the location where the error occurs. Once you know which function causes the error, you can use `debug` to step into the function and execute its code line by line when you use `SerialParam` to run the parallel evaluation locally.

Best,
Jiefei

**Comment by stefnoerman** [comment]
hi Jiefei,

thanks for the tips. yesterday i tried running register(SerialParam()) before the findChromPeaks function and i got this error message, which i understood that the error was in the rectUnique function. but i can try this also today.

do you have any suggestion how to run the debug function in batch SLURM job in a closed Linux environment ? Thanks a lot
![image](https://user-images.githubusercontent.com/94456030/142381318-8034e787-7dec-4d1c-b346-ede7de2215a6.png)
