### ISSUE TITLE
progressbar regression

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocParallel#172]
https://community-bioc.slack.com/archives/C34NC134G/p1637753385044400 reports that the progress bar has been replaced by an iterator.
```
> fun = function(i) { message(" working"); i }
> res = bplapply(1:10, fun, BPPARAM=MulticoreParam(2, progressbar=TRUE))
iteration: 1 working
2 working
3 working
4 working
5 working
6 working
7 working
8 working
9 working
10 working

>
```

**Comment by mtmorgan** [comment]
@Jiefei-Wang can you provide a pull request based on the RELEASE_3_14 branch?

**Comment by Jiefei-Wang** [comment]
Thanks, this is on my TODO list but I plan to fix it after the change in `BPREDO`. I can give it a quick fix on the RELEASE_3_14 branch.
