### ISSUE TITLE
ERROR: compilation failed for package 'BiocParallel'/g++: command not found

### ISSUE THREAD

**Issue by ewelinarubin** [Bioconductor/BiocParallel#213]
I am having trouble installing the package -- I get a few errors please see below 
Any recommendation on what to do ?

> if (!require("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
Bioconductor version 3.15 (BiocManager 1.30.18), R 4.2.0 (2022-04-22 ucrt)
> BiocManager::install("BiocParallel")
Bioconductor version 3.15 (BiocManager 1.30.18), R 4.2.0 (2022-04-22 ucrt)
Installing package(s) 'BiocParallel'

  There is a binary version available but the source version is
  later:
             binary source needs_compilation
BiocParallel 1.30.2 1.30.3              TRUE

installing the source package ‘BiocParallel’

trying URL 'https://bioconductor.org/packages/3.15/bioc/src/contrib/BiocParallel_1.30.3.tar.gz'
Content type 'application/x-gzip' length 895095 bytes (874 KB)
downloaded 874 KB

* installing *source* package 'BiocParallel' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.0/include" -DNDEBUG  -I'C:/Users/eweli/AppData/Local/R/win-library/4.2/BH/include'   -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c ipcmutex.cpp -o ipcmutex.o
sh: line 1: g++: command not found
make: *** [C:/PROGRA~1/R/R-42~1.0/etc/x64/Makeconf:259: ipcmutex.o] Error 127
ERROR: compilation failed for package 'BiocParallel'
* removing 'C:/Users/eweli/AppData/Local/R/win-library/4.2/BiocParallel'

The downloaded source packages are in
        ‘C:\Users\eweli\AppData\Local\Temp\Rtmp4kyZEA\downloaded_packages’
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.2.0/library
  packages:
    MASS
Warning message:
In install.packages(...) :
  installation of package ‘BiocParallel’ had non-zero exit status
>

**Comment by mtmorgan** [comment]
Usually at this stage
```
There is a binary version available but the source version is
later:
binary source needs_compilation
BiocParallel 1.30.2 1.30.3 TRUE
```
you are asked whether you wish to install the binary or the source package. Choose the binary package.

Alternatively, install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) to compile from source; this is NOT the best solution for most users.
