### ISSUE TITLE
Template file for Slurm job submission

### ISSUE THREAD

**Issue by mitmurakami** [Bioconductor/BiocParallel#222]
Hello,

I have trouble understanding the template file given in a vignettes example, as little explanation is given (Section 4.3.2).  The <% ... %> portion of the file seems like JSP scriptlet, but how do they get executed in bash script?  I cannot find anything like this anywhere on the internet search.  I want to separate the error output and log output files, but the example handles both as "log.file" - what is this keyword do?  Is it in R or in JSP?

**Comment by mtmorgan** [comment]
The templates are from the batchtools package https://cran.r-project.org/package=batchtools. From the [vignette](https://cran.r-project.org/web/packages/batchtools/vignettes/batchtools.html) the `<% ... %>` code come from use of the 'brew' package for template instantiation; it is not 'JSP'.

For the specific question about log versus output, it looks like the key line is https://github.com/mllg/batchtools/blob/63a6f812927f6dc78595abbffac0f6bc9651f67a/inst/templates/slurm-simple.tmpl#L27 and the solution would edit this template to use a different file for log versus output.
