### ISSUE TITLE
Error using conflicted with BiocParallel in R4.2.0 

### ISSUE THREAD

**Issue by hxin** [Bioconductor/BiocParallel#223]
Hi,

We have used conflict package with BiocParallel in our pipeline without issue with R 4.0.3.
We recently updated R to 4.2.0 we get an error as below:
Error: worker evaluation failed: there is no package called ‘.conflicts’

I have reported the issue in the conflict repository with detail to reproduce the issue at [here](https://github.com/r-lib/conflicted/issues/71), however just want to also mention it here as I am not sure if the issue is rooted in the conflict package or in BioParallel.

Thanks

**Comment by mtmorgan** [comment]
Thanks, I responded to the conflicted issue with

---
A recent version of BiocParallel tries to be 'smarter' about automatically exporting variables used in the parallel function. Turn this behavior off by adding `exportvariables = FALSE` to the `SnowParam()` object
```
> bplapply(c(1:2), prepare_worker, BPPARAM = SnowParam())
Error: BiocParallel errors
  2 remote errors, element index: 1, 2
  0 unevaluated and other errors
  first remote error:
Error: worker evaluation failed:
  there is no package called ‘.conflicts’
> bplapply(c(1:2), prepare_worker, BPPARAM = SnowParam(exportvariables=FALSE))
[[1]]
[1] "conflicted" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"

[[2]]
[1] "conflicted" "stats"      "graphics"   "grDevices"  "utils"
[6] "datasets"   "methods"    "base"
```
Thanks for the simple reproducible example!
---

but @Jiefei-Wang or I will be able to understand whether this particular problem can be avoided more directly so will leave the current issue open.

**Comment by hxin** [comment]
Thanks a lot for the quick reply. 

Adding the parameter _exportvariables = FALSE_ does solve the problem in the newer version, however, it seems that in the  _SnowParam_ function will check the parameter and raise an error if the parameter is not defined as input of the function. Is there a backward-compatible approach to solve this issue so our old script can still work with the newer version of BioParallel?

```R
 library(BiocParallel)
 conflict_prefer("strsplit", "base")
[conflicted] Will prefer base::strsplit over any other package
 para <- SnowParam(workers = 2, stop.on.error = TRUE, jobname = 'test',
     log = TRUE, threshold = "DEBUG", logdir = "/tmp", tasks = 2,  exportvariables = FALSE)
Error in .prototype_update(.SnowParam_prototype, .clusterargs = clusterargs,  :
  all(names(args) %in% names(prototype)) is not TRUE
```

**Comment by mtmorgan** [comment]
Create the param and update if in the newer version?
```
p = SnowParam()
if (packageVersion("BiocParallel") >= "1.30.0")
    bpexportvariables(p) <- FALSE
```

**Comment by hxin** [comment]
Thank you for the response. What I mean was to have the new version work without changing the old scripts. 
For example, if the _exportvariables_ is by default _FLASE_, then it will not create this issue in the old scripts. Or if there is a way to globally control the default value of this parameter so I don't need to change anything in the old scripts?
something like below:
```bash
echo 'exportvariables = FALSE ' >> .Rprofile
Rscript old_script.R
````

**Comment by hxin** [comment]
Thank you very much for your help.

**Comment by Jiefei-Wang** [comment]
> A recent version of BiocParallel tries to be 'smarter' about automatically exporting variables used in the parallel function.

This is the case where BiocParallel is not 'smarter' enough...

The root problem is that the function `utils::find` used in BiocParallel to search for undefined symbols can return internal objects. I do not exactly know what `.conflicts` is for but it seems necessary to filter these internal names out. I can create a pull request to fix this issue.
