### ISSUE TITLE
Converting Introduction to BiocParallel.rnw to R Markdown

### ISSUE THREAD

**Issue by phyleria** [Bioconductor/BiocParallel#225]
Hi,

I'm volunteering with [Sweave2Rmd](https://github.com/Bioconductor/sweave2rmd)
and we're trying to replace all Bioconductor Sweave vignettes R Markdown
vignettes. Would you be willing to accept a pull request with the R Markdown
version of  `Introduction to BiocParallel.Rnw`   from me as a contributor.  I'll kindly ask you to
review and accept the pull request. You'll also need to bump the version
number in your DESCRIPTION file so that the build machines will recognize
that a new version is available.

Thanks for your time.

**Comment by mtmorgan** [comment]
Yes your pull request would be accepted. In addition to the Sweave2Rmd instructions, please be sure that the DESCRIPTION file has been edited to contain your (real) given and family name, indicate `role = "ctb"` and `comment = "converted BiocParallel.Rnw to BiocParallel.Rmd"`.

**Comment by phyleria** [comment]
Thank you @mtmorgan 
I'll be sure to add those details to the DESCRIPTION file

**Comment by mtmorgan** [comment]
I look forward to your contribution! This issue https://github.com/Bioconductor/sweave2rmd/issues/34#issuecomment-1279746231 might point to a useful workflow; the vignette makes use of LaTeX macros that are silently 'dropped' by pandoc.

**Comment by phyleria** [comment]
Thank you so much @mtmorgan , that is important to note!
