### ISSUE TITLE
Add function to check for non-local variable use

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocParallel#25]
The [80/20 solution](https://stat.ethz.ch/pipermail/bioc-devel/2013-November/004884.html) is probably ambitious enough

**Comment by mtmorgan** [comment]
bpvalidate() implements this functionality (??).

**Comment by HenrikBengtsson** [comment]
See my/the [globals](https://cran.r-project.org/package=globals) package, which has the objective of identifying globals ("unknowns") in expressions through static code inspection.
