### ISSUE TITLE
Extremely minor: typo in docs? man/MulticoreParam-class.Rd

### ISSUE THREAD

**Issue by adam-cornwell** [Bioconductor/BiocParallel#258]
MulticoreParam
force.GC:
"logical(1) Whether to invoke the garbage collector after each call to FUN. The value TRUE, explicitly call the garbage collection, can slow parallel computation, but is necessary when each call to FUN allocates a 'large' amount of memory. If FUN allocates little memory, **then considerable performance improvements are gained by the default setting force.GC = TRUE**. "

The default setting is "FALSE" and it's pretty likely that setting it to TRUE when it's not necessary would reduce performance.

About the most minor possible issue but wanted to point it out. I figured it wasn't worth a pull request.
Thanks!

**Comment by mtmorgan** [comment]
Sorry to be so slow!
