### ISSUE TITLE
bplist_error does not report the error element index

### ISSUE THREAD

**Issue by ChangqingW** [Bioconductor/BiocParallel#263]
I was debugging my function with the following:
```{r}
variants <- tryCatch({
  BiocParallel::bpmapply(
  ...
    BPPARAM = BiocParallel::MulticoreParam(
      workers = threads, stop.on.error = TRUE, progressbar = FALSE 
    )
  )
}, error = identity)

if (inherits(variants, "error")) {
  warning("Error occurred in `sc_mutations`, returning error object")
  return(variants)
}
```

But the `bplist_error` does not report the error element index when I was using my full dataset:
```
<bplist_error: BiocParallel errors
  0 remote errors, element index:
  17 unevaluated and other errors
  first remote error:
>
results and errors available as 'bpresult(x)'
```

I had to do a manual binary search, when I reduced it to 3 jobs, `bplist_error` works normally again:
```
<bplist_error: BiocParallel errors
  1 remote errors, element index: 3
  0 unevaluated and other errors
  first remote error:
Error in tidyr::pivot_longer(tibble::as_tibble(variant_count_matrix(bam_path = bam_path, : `cols` must select at least one column.
>
results and errors available as 'bpresult(x)'
```

I was wondering why the `bplist_error` object includes no information about the error when I had >= 5 jobs

**Comment by mtmorgan** [comment]
Can you make a reproducible example, e.g., `res <- bptry(bplapply(1:20, \(x) stop("oops ", i)))` and indicate what the problem is? The '[Errors and Debugging](https://bioconductor.org/packages/release/bioc/vignettes/BiocParallel/inst/doc/Errors_Logs_And_Debugging.pdf)' vignette might also be relevant.

**Comment by Jiefei-Wang** [comment]
Just trying to throw a stone in the dark. Probably this is because the workers died. There is no error but 17 unevaluated. How many jobs do you have? A reprex will be helpful. Also, try to set `stop.on.error=FALSE` to see if this gives you something.

**Comment by ChangqingW** [comment]
> Just trying to throw a stone in the dark. Probably this is because the workers died. There is no error but 17 unevaluated. How many jobs do you have? A reprex will be helpful. Also, try to set `stop.on.error=FALSE` to see if this gives you something.

I had ~800 jobs, was halving it and got `bplist_error` to properly report the error index when I got down to 5 jobs.
I checked my logs and found this:
```
  |===============================================================       |  90%Stop worker failed with the error: wrong args for environment subassignment
```

I am having trouble to come up with a minimal reproducible example, if I replace my Rcpp function with a dummy function the `bplist_error` reports the index perfectly fine again and I don't get the `Stop worker failed` message. I suppose the "stop worker" is needed to report the error element index then?

**Comment by ChangqingW** [comment]
Closing as I can't seem to come up with a minimal example. I guess it must be something in my spaghetti code killing the stop worker.
