### ISSUE TITLE
Symbols evaluated too eagerly

### ISSUE THREAD

**Issue by mllg** [Bioconductor/BiocParallel#30]
Compability issue with virtualArray. 

```splus
bplapply(list(as.symbol("x")), as.character, 
  BPPARAM=SerialParam(catch.errors=TRUE))
```
throws an error if `catch.errors==TRUE`, which is the default.

* Change default to `FALSE` (at least until error handling is really well tested to deal with language objects)
* Test all backends to not resolve symbols too eagerly

**Comment by vobencha** [comment]
Closing this issue.
