### ISSUE TITLE
Using on an LSF cluster - "Some jobs disappeared"

### ISSUE THREAD

**Issue by zslastman** [Bioconductor/BiocParallel#43]
Hi, your package is potentially really useful to me, but I'm having an issue where, although to toy examples work, scaling up to many jobs gives an error message:

Error in stop(e) :
  Some jobs disappeared, i.e. were submitted but are now gone. Check your configuration and template file.

E.g., I can do 

#toy function
FUN <- function(x) { round(sqrt(x), 4) }
#now with batch
funs <- makeClusterFunctionsLSF("/g/furlong/Harnett/Tagseq_myfolder/jobs/simple.tmpl")
param <- BatchJobsParam(4, resources=list(ncpus=1,nodes=1,queue = 'medium_priority' ,memory=1e4,walltime=3600),cluster.functions=funs)
register(param)
xx <- bplapply(1:20, FUN)

But if I do the following:
xx <- bplapply(1:200, FUN)

Then I generally get the error.
Maybe BioCparallel just needs to wait longer for the LSF scheduler to return the jobs? I don't generally get problems with the cluster dropping jobs otherwise, and the R code isn't at fault.

Thanks for you help!

**Comment by vobencha** [comment]
Hi,
Michel is the better  person to answer this question but I can clarify that BiocParallel passes control over to BatchJobs and does not decide when the scheduler should return jobs. 

The error you see is from the BatchJobs package and indicates a problem with the template / config set up. Are you using a config file in addition to the template? If yes, do these have conflicting information? You could try adding a log file to he template (example in [ls11.tmpl]{https://github.com/tudo-r/BatchJobs/blob/master/examples/cfLSF/ls11.tmpl}) which may give more info about what is going on.

Valerie

**Comment by zslastman** [comment]
Hi vobencha, thanks for the quick reply.

So. 
Removing the template file (ie. not setting cluster.functions) causes the code to work, but submission takes a *long* time - minutes - despite the fact that I'm only passing an integer to each job.
Using this template file directly with Batch jobs doesn't give any problems.
Setting a log file and looking at it , as you suggest, shows that the jobs complete, but then yield:

cat: write error: Input/output error

**Comment by mllg** [comment]
Hi,

Not using any template results in a sequential execution, thus the submission taking so long is kind of expected: All jobs run now on the master and `submitJobs()` wait for each of them before submitting the next one.

> Error in stop(e) :
> Some jobs disappeared, i.e. were submitted but are now gone. Check your configuration and template file.

Can you give me a `traceback()` for this one? Also, what is the last output you are getting?

> Setting a log file and looking at it , as you suggest, shows that the jobs complete, but then yield:
> 
> cat: write error: Input/output error

That went wrong, the redirection does not seem to work here. If possible, please provide your configuration and template file.

> param <- BatchJobsParam(4, resources=list(ncpus=1,nodes=1,queue = 'medium_priority' ,memory=1e4,walltime=3600),cluster.functions=funs)

Please remove the `4` and try again. Also, make sure that your current working directory (`getwd()`) points to a directory which is shared with all nodes or set it explicitly: your `file.dir` will be created in a subdirectory of `work.dir`. Set `cleanup = FALSE` so that it will not be automatically deleted after the exception which allows you load the registry after the error and get more insight into what is going wrong.

**Comment by zslastman** [comment]
Hi, thanks for your help.
Removing the 4 doesn't help. My working directory is accessible from the the nodes (at least, the jobs that finish with Batchjobs are able to see it). However,looking again at the batchjobs output it seems batchjobs also fails to return some jobs, it just doesn't give an error message like bioCparallel. I guess this means the problem is on their end, so I'll go on over to the batchjobs git hub and bother them :)

In case you're still interested, here's the traceback, template file, and config file:


########Traceback:

Error in stop(e) :
  Some jobs disappeared, i.e. were submitted but are now gone. Check your configuration and template file.

> traceback()
10: stop("Some jobs disappeared, i.e. were submitted but are now gone. Check your configuration and template file.")
9: stop(e)
8: bar$error(stop("Some jobs disappeared, i.e. were submitted but are now gone. Check your configuration and template file."))
7: waitForJobs(reg, ids, timeout = Inf, stop.on.error = (BPPARAM$stop.on.error &&
       !BPPARAM$catch.errors))
6: bpmapply(FUN, X, MoreArgs = list(...), SIMPLIFY = FALSE, BPRESUME = BPRESUME,
       BPPARAM = BPPARAM)
5: bpmapply(FUN, X, MoreArgs = list(...), SIMPLIFY = FALSE, BPRESUME = BPRESUME,
       BPPARAM = BPPARAM)
4: bplapply(X, FUN, ..., BPRESUME = BPRESUME, BPPARAM = BPPARAM)
3: bplapply(X, FUN, ..., BPRESUME = BPRESUME, BPPARAM = BPPARAM)
2: bplapply(1:4, FUN)
1: bplapply(1:4, FUN)


###########Configfile
cluster.functions = makeClusterFunctionsLSF("/g/furlong/Harnett/Tagseq_myfolder/jobs/simple.tmpl")
mail.start = "none"
mail.done = "none"
mail.error = "none"
db.driver = "SQLite"
db.options = list()
debug = FALSE

#############Template file


## Default resources can be set in your .BatchJobs.R by defining the variable 
## 'default.resources' as a named list.

## remove everthing in [] if your cluster does not support arrayjobs
#BSUB-J <%= job.name %>[1-<%= arrayjobs %>]         # name of the job / array jobs
#BSUB-o <%= log.file %>                             # output is sent to logfile, stdout + stderr by default
#BSUB-q <%= resources$queue %>                      # Job queue
#BSUB-W <%= resources$walltime %>                   # Walltime in minutes
#BSUB-M <%= resources$memory %>                     # Memory requirements in Kbytes

# we merge R output with stdout from LSF, which gets then logged via -o option
R CMD BATCH --no-save --no-restore "<%= rscript %>" /dev/stdout

**Comment by vobencha** [comment]
Closing this issue.

**Comment by mfansler** [comment]
I had a similar issue and was able to resolve by setting the `max.concurrent.jobs` value in my configuration file.  I didn't see any docs stating there was an explicit limit on concurrent submissions for our cluster, but empirically, I saw jobs consistently disappear at $N >= 40$.  

I ended up using `max.concurrent.jobs = 32` which, for all practical purposes, has been reasonable for my uses.
