### ISSUE TITLE
Rscript: trying to execute load actions without 'methods' package

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/BiocParallel#44]
Does the following to be fixed in Bioc release?

With BiocParallel 1.4.0 on R (<= 3.2.3), I get:
```r
% Rscript --version
R scripting front-end version 3.2.3 Patched (2015-12-10 r69760)

% Rscript -e "loadNamespace('BiocParallel')"
<environment: namespace:BiocParallel>
Warning message:
In .doLoadActions(where, attach) :
  trying to execute load actions without 'methods' package
```
I don't understand why this happens, because the `methods` is listed under `Depends:`.

I do _not_ see this with BiocParallel 1.5.0 on R devel;
```r
% Rscript --version
R scripting front-end version 3.3.0 Under development (unstable) (2015-12-10 r69760)
% Rscript -e "loadNamespace('BiocParallel')"
<environment: namespace:BiocParallel>
```

**Comment by mtmorgan** [comment]
The source of the error is in RMethodUtils.R, and was changed (removed) with this commit https://github.com/wch/r-source/commit/d502da038d0e93e73bf3220ec668022445ef44fc -- I think the message is annoying but not indicating a problem.

**Comment by HenrikBengtsson** [comment]
Ok. Thanks for the explanation.
