### ISSUE TITLE
bpslaveLoop uses both parallel & snow for communication

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocParallel#49]
send/recvData() via parallel, but snow::closeNode(). Should only use one package (parallel?)

**Comment by DarwinAwardWinner** [comment]
To my knowledge, the parallel package is supposed to subsume both snow and multicore packages, so presumably it should just be using that one.

**Comment by mtmorgan** [comment]
The code was such that closeNode came from snow for SnowParam(), but from parallel for MulticoreParam(). It seems to be ok to use parallel::closeNode, finalized in https://github.com/Bioconductor/BiocParallel/commit/25827575b4d7e173cf890b98281fcc0d15813c18.
