### ISSUE TITLE
In vignette, update reference to Statistical Science article.

### ISSUE THREAD

**Issue by JoshOBrien** [Bioconductor/BiocParallel#52]
Since it was published, in 2014, the included URL (http://www.imstat.org/sts/future papers.html) is no longer useful.

**Comment by mtmorgan** [comment]
Thanks closed with 74438f925f020003cee573e798ba75f83b8f5736 with updated URL http://arxiv.org/abs/1409.2864

**Comment by lawremi** [comment]
Hey Martin, are you aware that you can include "fixes #52" in the commit message to automatically close this with a reference?

**Comment by mtmorgan** [comment]
@lawremi Via svn? I'll try next time.
