### ISSUE TITLE
bpiterate problem

### ISSUE THREAD

**Issue by daewoooo** [Bioconductor/BiocParallel#58]
Dear BiocParallel developers,

I have some trouble getting bpiterate function to run in parallel on my PC. I'm running linux PC (ubuntu 14.04). To run the code I'm using RStudio and R version  3.2.2 . I'm trying to process bam file sorted by Qnames in chunk and apply function to each chunk.
While it seems that multicore processing of the bam file is working in parallel (based on memory consumption) loaded chunks are not processed in parallel (based on CPU usage). I did get any error while running the code, the only problem is that I'm still using only one CPU.
Can you please help me to solve this problem?
Below is the code I used trying to reproduce example code from the reference manual from BiocParallel package.

Thank you in advance,
David

####################################################################

```
bf <- BamFile(bamfile, yieldSize = 300000, obeyQname=TRUE)

bamIterator <- function(bf) {
  done <- FALSE
  if (!isOpen( bf))
    open(bf)
  function() {
    if (done)
      return(NULL)
    param <- Rsamtools::ScanBamParam(
        what=c('seq', 'qual','mapq','cigar'),  
        flag=scanBamFlag(isDuplicate=F))
    yld <- readGAlignments(bf, param=)
    if (length(yld) == 0L) {
      close(bf)
      done <<- TRUE
      NULL
    } else yld
  }
}

ITER <- bamIterator(bf)
bpparam <- MulticoreParam(workers = 4)

counter <- function(reads, roi, ...) {
  countOverlaps(query = roi, subject = reads)
} 

#hap.gr is GRanges object of multiple ranges
bpiterate(ITER, counter, roi=hap.gr, BPPARAM = bpparam)
```

**Comment by mtmorgan** [comment]
It's better to ask questions about use on the Bioconductor [support site](https://support.bioconductor.org). If I/O is slow relative to the chunked operation, then it will seem like there is only one processor (the reader) ever doing any work, the others are waiting around to do their quick counting. In this situation it is better to increase the yieldSize (10x?) and process using SerialParam().
