### ISSUE TITLE
biocParallel install error; makePSOCKcluster

### ISSUE THREAD

**Issue by billytcl** [Bioconductor/BiocParallel#62]
R 3.2.5

I'm having this issue when installing from biocLite:

> > biocLite("BiocParallel")
> BioC_mirror: http://bioconductor.org
> Using Bioconductor version 2.12 (BiocInstaller 1.10.4), R version 3.2.5.
> Temporarily using Bioconductor version 2.12
> Installing package(s) 'BiocParallel'
> --2017-02-04 15:22:35--  http://bioconductor.org/packages/2.12/bioc/src/contrib/BiocParallel_0.2.0.tar.gz
> Resolving bioconductor.org (bioconductor.org)... 54.192.147.23, 54.192.147.170, 54.192.147.156, ...
> Connecting to bioconductor.org (bioconductor.org)|54.192.147.23|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 126165 (123K) [application/x-gzip]
> Saving to: `/tmp/RtmpBv2SbE/downloaded_packages/BiocParallel_0.2.0.tar.gz'
> 
>      0K .......... .......... .......... .......... .......... 40% 1.35M 0s
>     50K .......... .......... .......... .......... .......... 81% 2.36M 0s
>    100K .......... .......... ...                             100% 7.25M=0.06s
> 
> 2017-02-04 15:22:35 (2.01 MB/s) - `/tmp/RtmpBv2SbE/downloaded_packages/BiocParallel_0.2.0.tar.gz' saved [126165/126165]
> 
> * installing *source* package ‘BiocParallel’ ...
> ** R
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> Error : .onLoad failed in loadNamespace() for 'BiocParallel', details:
>   call: makePSOCKcluster(spec, ...)
>   error: numeric 'names' must be >= 1
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing ‘/home/billylau/R/x86_64-pc-linux-gnu-library/3.2/BiocParallel’
> 
> The downloaded source packages are in
> 	‘/tmp/RtmpBv2SbE/downloaded_packages’

Any ideas?

**Comment by mtmorgan** [comment]
Your version of BiocInstaller (which determines the version of Bioconductor) is not appropriate for R version 3.2.5. From the [release announcements](http://bioconductor.org/about/release-announcements/) you should be using Bioconductor 3.1 or 3.2. Likely you need to follow [these directions](http://bioconductor.org/install/#troubleshoot-biocinstaller) to remove all versions of BiocInstaller, then try again.
