### ISSUE TITLE
Migration to batchtools

### ISSUE THREAD

**Issue by mfansler** [Bioconductor/BiocParallel#64]
Are there any plans to migrate away from **BatchJobs** to its successor, **[batchtools](https://mllg.github.io/batchtools/index.html)**?

If not, would a contributed PR be accepted?  For instance, one could write a `BatchToolsParam` class paralleling the `BatchJobsParam` one, and then eventually mark the `BatchJobsParam` as deprecated (e.g., throws a warning when using) once the `BatchToolsParam` has been verified to be stable across different platforms.

**Comment by mtmorgan** [comment]
A pull request would be  great incentive for this, yes.

**Comment by DarwinAwardWinner** [comment]
Based on the existence of [future.batchtools](https://cran.r-project.org/web/packages/future.batchtools/index.html), I suggest it might be better to write a backend for [future](https://cran.r-project.org/web/packages/future/index.html) and get batchtools support for free. The downside is that such a solution might not support the more advanced features of batchtools, so it depends on what batchtools features BiocParallel needs.

**Comment by DarwinAwardWinner** [comment]
Actually, I just noticed that @HenrikBengtsson appears to have already done so: https://github.com/HenrikBengtsson/BiocParallel.FutureParam. So maybe BiocParallel already supports batchtools through the future package.

**Comment by mfansler** [comment]
@DarwinAwardWinner Nice! I hadn't seen that library previously.  Rather new, but looks promising.

I still think it would be useful to integrate such functionality directly into **BiocParallel** rather than having an additional dependency.

**Comment by mllg** [comment]
I don't have time to migrate this myself in the next 2-3 month, but I could export functions and complement missing helpers in `batchtools` if someone wants to start working on a PR.

**Comment by HenrikBengtsson** [comment]
I'm willing to contribute the code of [BiocParallel.FutureParam](https://github.com/HenrikBengtsson/BiocParallel.FutureParam) to the BiocParallel package.  That way BiocParallel would support all backends that implement the Future API, including [future.batchtools](https://CRAN.R-project.org/package=future.batchtools) (and hence batchtools).  All the end user would do is `register(FutureParam)` and select what future backend to use via `future::plan()`.  One can of course come up with a `register()` call that does both in one go, but to keep it simple, I haven't done so for now.

BTW, in lieu of FutureParam, a working solution to utilize (future.)batchtools in BiocParallel is to go via [doFuture](https://CRAN.R-project.org/package=doFuture) and DoParParam, e.g.

```r
library("BiocParallel")
register(DoparParam(), default = TRUE)
doFuture::registerDoFuture()

library("future.batchtools")
plan(batchtools_local)

y <- bplapply(X = 1:3, FUN = function(x) list(x = x, pid = Sys.getpid()))
str(y)
## List of 3
##  $ :List of 2
##   ..$ x  : int 1
##   ..$ pid: int 26553
##  $ :List of 2
##   ..$ x  : int 2
##   ..$ pid: int 26554
##  $ :List of 2
##   ..$ x  : int 3
##   ..$ pid: int 26555
```

PS. This solution illustrates the goal of the future package; to bridge parallel frontends with parallel backends by providing a backend API that parallel backends implement and a frontend API that higher-level APIs implement.

**Comment by DarwinAwardWinner** [comment]
I guess the question is, is there any special functionality provided by batchtools that BiocParallel needs/wants to access and which is not exposed through the Future API? If not, then I would consider this pretty much solved.

**Comment by mtmorgan** [comment]
It seemed like the future api was also committing to a particular programming style (of unevaluated expressions)?

**Comment by HenrikBengtsson** [comment]
There's
```r
f <- future({ expr })
```
and
```r
f <- futureCall(FUN, args)
```
Is that what you're looking for, or did you mean something else?  The other two key components of the frontend Future API are
```r
resolved(f)
```
to check if future is resolved or not, and
```r
v <- value(f)
```
to collect the value (or signal error if it occurred).  The idea is that those are the building blocks for higher level needs.  There's also `resolved(fs)` and `values(fs)` which operate on a set of futures, e.g. a list of futures.

Certain features such as stopping ("killing") futures are not part of the frontend Future API.  This might be added in the future, cf. https://github.com/HenrikBengtsson/future/issues/93 (long story).

**Comment by HenrikBengtsson** [comment]
Coming back to this one.  Not sure if my most recent reply helped or caused confusion.

From the end user's point of view, futures just provide another backend that the user can register for BiocParallel, i.e. `register(FutureParam)`.  Everything else will work the same.  It should be 100% compatible with the BiocParallel API.

For the actual internals of the FutureParam backend, there are a few alternatives, but my existing working [proposal](https://github.com/HenrikBengtsson/BiocParallel.FutureParam/blob/master/R/FutureParam-class.R) shows how it can be done.  There might be features in BiocParallel that I'm not aware of and that's missing, but the [package tests against the existing BiocParallel API that I'm aware of](https://github.com/HenrikBengtsson/BiocParallel.FutureParam/tree/master/tests).

Let me know if you want me to do a PR of what I've got.

**Comment by nturaga** [comment]
Hi,

There is now a `BatchtoolsParam-class` implemented with some basic functionality. It is on pull request #71 , which was just merged with master. 

Please take a look. 

Best,

Nitesh

**Comment by nturaga** [comment]
Hi, the latest extension has been merged. Please take a look at #72 .
