### ISSUE TITLE
src/ipcmutex.cpp: Is this used anywhere?

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/BiocParallel#80]
Troubleshooting an installation issue that I narrowed down to compiling `src/ipcmutex.cpp`, I noticed that this native code is called in R/ipcmutex.R but none of those R functions are used in any of the BiocParallel code;
```sh
grep -E "ipc.+" */*.R
R/ipcmutex.R:ipcid <- function(id) {
R/ipcmutex.R:    uuid <- .Call(.ipc_uuid)
R/ipcmutex.R:ipcremove <- function(id) {
R/ipcmutex.R:    invisible(.Call(.ipc_remove, id))
R/ipcmutex.R:ipclocked <- function(id)
R/ipcmutex.R:    .Call(.ipc_locked, id)
R/ipcmutex.R:ipclock <- function(id) {
R/ipcmutex.R:    .Call(.ipc_lock, id)
R/ipcmutex.R:ipctrylock <- function(id) {
R/ipcmutex.R:    .Call(.ipc_try_lock, id)
R/ipcmutex.R:ipcunlock <- function(id) {
R/ipcmutex.R:    .Call(.ipc_unlock, id)
R/ipcmutex.R:ipcyield <- function(id) {
R/ipcmutex.R:    .Call(.ipc_yield, id)
R/ipcmutex.R:ipcvalue <- function(id) {
R/ipcmutex.R:    .Call(.ipc_value, id)
R/ipcmutex.R:ipcreset <- function(id, n = 1) {
R/ipcmutex.R:    invisible(.Call(.ipc_reset, id, n))
```
Are those function legacy functions?  Any known usages of those elsewhere?

**Comment by PeteHaitch** [comment]
AFAIK these are intended as helper functions for package developers using **BIocParallel* for paralellisation where the code requires locks/mutexs.
For example, I'm using these in **bsseq** to perform file locking within a routine paralellised with **BiocParallel** (https://github.com/hansenlab/bsseq/blob/refactor/R/read.bismark.R)

**Comment by HenrikBengtsson** [comment]
Thanks - this is useful.

Just a thought: Since this is the only native code in BiocParallel and it uses (I think) very low-level (kernel?) calls, it could be that others run into problems in building it on "obscure" environments like mine (too long story for me to explain my use case).  Would it make sense to put that code in a standalone "mutex" package instead?

Comment about file locks: Those file locks in bsseq assumes that the code is parallelize on the local machine, correct?  If parallelizing across multiple machines on a shared file system, I don't think you can trust file locks, can you?

**Comment by mtmorgan** [comment]
@HenrikBengtsson They're not legacy functions at all. Can you provide the problem you actually experienced? For context, the work is delegated to boost library calls from the following headers

```
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>
...
#include <boost/interprocess/managed_shared_memory.hpp>
#include <boost/interprocess/sync/interprocess_mutex.hpp>
```

I originally developed the locks in the context of a single machine (`MulticoreParam()`, which is like `parallel::mclapply()`) ; they definitely don't work across a generic cluster, because the locks are machine-specific; I'd be surprised if the locks were written to the shared system.

**Comment by HenrikBengtsson** [comment]
Again, there's nothing wrong with BiocParallel here. The problem on my end is due to a broken system, causing installation issues:
```
* installing *source* package ‘BiocParallel’ ...
** libs
/opt/gcc/gcc-4.9.2/bin/g++ -std=gnu++11 -I"/path/to/lib64/R/include" -DNDEBUG  -I"/home/henrik/tmp-rlibs/BH/include" -I/usr/local/include   -fpic  -g -O2 -c ipcmutex.cpp -o ipcmutex.o
/opt/gcc/gcc-4.9.2/bin/g++ -std=gnu++11 -shared -o BiocParallel.so ipcmutex.o
/usr/lib/crti.o: could not read symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: *** [BiocParallel.so] Error 1
ERROR: compilation failed for package ‘BiocParallel’
* removing ‘/home/henrik/tmp-rlibs/BiocParallel’
```
However, this is solely due to an invalid `/usr/lib/crti.o` which cannot be easily be fixed.

**Comment by PeteHaitch** [comment]
> Comment about file locks: Those file locks in bsseq assumes that the code is parallelize on the local machine, correct? If parallelizing across multiple machines on a shared file system, I don't think you can trust file locks, can you?

@HenrikBengtsson Correct. I have some (somewhat clunky and probably hacky) logic in those functions to check the compatibility of the parallelisation backend with the file locking strategy, as well as the somewhat related *DelayedArray* backend (https://github.com/hansenlab/bsseq/blob/296c9077509486c92660a5fc648bbc0243c158b2/R/read.bismark.R#L408-L426)
