### ISSUE TITLE
bplapply with BatchtoolsParam does not acknowledge List objects

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocParallel#82]
It seems as if `bplapply` doesn't acknowledge that one can loop over `List`s:

```r
library(BiocParallel)
BPPARAM <- BatchtoolsParam(10, 
        cluster="slurm", template="parallel/slurm-aaron.tmpl", 
        logdir="parallel", log=TRUE, 
        RNGseed=10000L,
        resources=list(walltime=20000, memory=8000, ncpus=1))

library(S4Vectors)
X <- as(as.list(1:10), "List")
Y <- bplapply(X, identity, BPPARAM=BPPARAM)
## Adding 1 jobs ...
## Submitting 1 jobs in 1 chunks using cluster functions 'Slurm' ...
## 
## cleaning registry...
str(Y)
## List of 1
##  $ : int 10
Z <- bplapply(as.list(X), identity, BPPARAM=BPPARAM)
## Adding 10 jobs ...
## Submitting 10 jobs in 10 chunks using cluster functions 'Slurm' ...
##                                                                               
## cleaning registry...
str(Z)
## List of 10
##  $ : int 1
##  $ : int 2
##  $ : int 3
##  $ : int 4
##  $ : int 5
##  $ : int 6
##  $ : int 7
##  $ : int 8
##  $ : int 9
##  $ : int 10
```

You can see that only one job gets submitted for `Y` (and the output isn't even right), whereas 10 jobs are submitted for `Z`. This behaviour does not occur for `SnowParam`, so I would assume that this is not a namespace issue. Indeed, the only thing that gets sent to the workers would be `identity` and an integer value, which shouldn't require any additional loading of packages in each worker.

<details>
<summary>Session information</summary>

```
R version 3.5.1 Patched (2018-09-06 r75247)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /home/jmlab/software/R/R-3-5-branch_devel/lib/libRblas.so
LAPACK: /home/jmlab/software/R/R-3-5-branch_devel/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] S4Vectors_0.19.19    BiocGenerics_0.27.1  BiocParallel_1.15.12

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18      batchtools_0.9.11 snow_0.4-3        prettyunits_1.0.2
 [5] withr_2.1.2       assertthat_0.2.0  digest_0.6.17     crayon_1.3.4     
 [9] rappdirs_0.3.1    R6_2.2.2          backports_1.1.2   magrittr_1.5     
[13] rlang_0.2.2       progress_1.2.0    stringi_1.2.4     fs_1.2.6         
[17] data.table_1.11.6 brew_1.0-6        checkmate_1.8.5   tools_3.5.1      
[21] hms_0.4.2         compiler_3.5.1    pkgconfig_2.0.2   base64url_1.4    
```
</details>

**Comment by DarwinAwardWinner** [comment]
Obviously this is not a real solution, but if you need a workaround to make this work right now, you can try using FutureParam with the batchtools backend for future: https://github.com/HenrikBengtsson/BiocParallel.FutureParam#futureparam-replaces-existing-biocparallelparam-classes

**Comment by mtmorgan** [comment]
The problem is deep in Batchtools, where it creates a data.table of tasks, analogous to

```
d2 <- data.table::as.data.table(list(List(1,2)))
```

(this object is corrupt, which is apparent when one tries to print it).

A workaround is to define an appropriate method

```
setMethod(
    bplapply, c("List", "BatchtoolsParam"),
    function(X, FUN, ..., BPREDO = list(), BPPARAM = bpparam())
{
    bplapply(as.list(X), FUN, ..., BPREDO = BPREDO, BPPARAM = BPPARAM)
})
```

if one is willing to pay the cost of coercing List to list. Another implementation is

```
setMethod(
    bplapply, c("List", "BatchtoolsParam"),
    function(X, FUN, ..., BPREDO = list(), BPPARAM = bpparam())
{
    X1 <- seq_along(X)
    FUN1 <- function(i, ...) FUN(X1[[i]], ...)
    bplapply(X1, FUN1, ..., BPREDO = BPREDO, BPPARAM = BPPARAM)
})
```
if one is willing to serialize X to all the workers. There is also a `bpiterate()` solution
```
setMethod(
    bplapply, c("List", "BatchtoolsParam"),
    function(X, FUN, ..., BPREDO = list(), BPPARAM = bpparam())
{
    ITER <- function(X) {
        i <- 0
        function() {
            if (i == length(X))
                return(NULL)
            i <<- i + 1L
            X[[i]]
        }
    }
    bpiterate(ITER(X), FUN, ..., BPPARAM = BPPARAM)
})
```
if one doesn't want to support BPREDO

**Comment by LTLA** [comment]
I would think that Door \#1 would be the simplest approach? Surely a `list` coercion shouldn't be that expensive, it's just juggling `SEXP`s around.

**Comment by DarwinAwardWinner** [comment]
Wouldn't it be better to write a separate method with a signature of `setMethod("bplapply", c("List", "BatchtoolsParam"), ...)`? Also, is there a need to convert the returned result back from a `list` to a `List`?

**Comment by DarwinAwardWinner** [comment]
E.g. something like:

```R
setMethod("bplapply", c("List", "BatchtoolsParam"),
	          function(X, FUN, ..., BPREDO = list(), BPPARAM=bpparam())
{
    X2 <- as.list(X)
    result <- bplapply(X2, FUN = FUN, ..., BPREDO = BPREDO, BPPARAM = BPPARAM)
    as(result, "List")
})
```

**Comment by mtmorgan** [comment]
Writing a method for List would introduce a dependency in BiocParallel on S4Vectors, or implementing an elaborate `?packageEvent()` hook which I don't trust to be robust. `bplapply()` does not make any statement about returning an endomorphism,  though I guess that's a reasonable feature...

**Comment by DarwinAwardWinner** [comment]
Presumably `bplapply` should do its best to return the same as `lapply`. Since `lapply` on a `List` returns a `list`, I suppose `bplapply should do the same. Instead, maybe we also need `bpendoapply`, although for the reasons you give, it might not be possible to provide such a function in the BiocParallel package itself.
