### ISSUE TITLE
Errors with logging using SnowParam

### ISSUE THREAD

**Issue by David-J-R** [Bioconductor/BiocParallel#83]
Dear BiocParallel Team,

I'm using your package for the parallelisation of the Bioconductor package BEclear, which I maintain. 
And I noticed, that everytime I use SnowParam for evaluation, I get the error: 
  `could not find function "flog.debug" `
Similar for the other logging functions of the futile.logger package.
I call the SnowParam functions like this:
`bpparam <- SnowParam(log=TRUE, progressbar = TRUE)`

Am I doing something wrong here or is this an issue with the Snow as an evaluation system?

**Comment by mtmorgan** [comment]
Can you provide a simple reproducible example? `flog.debug` isn't used in BiocParallel except in the vignette, so I guess the issue involves your own code in some way?

**Comment by David-J-R** [comment]
Of course! The simplest example I can think of is:
`library(BiocParallel)
library(futile.logger)

fun <- function(v) {
    flog.debug(v)
}
bplapply(1:10, fun)`

And it also return:

`Error: BiocParallel errors
  element index: 1, 2, 3, 4, 5, 6, ...
  first error: could not find function "flog.debug"`

**Comment by PeteHaitch** [comment]
With *SnowParam* you need to load the required packages on the worker (see section 4.1.2 of https://bioconductor.org/packages/release/bioc/vignettes/BiocParallel/inst/doc/Introduction_To_BiocParallel.pdf).

So I think you need to make your example:

```R
library(BiocParallel)

fun <- function(v) {
  library(futile.logger)
  flog.debug(v)
}
bplapply(1:10, fun, BPPARAM = SnowParam())
```

**Comment by David-J-R** [comment]
Alright... I see. But as BiocParallel uses futile.logger for logging. Shouldn't it be loaded by default?

**Comment by mtmorgan** [comment]
It's loaded in the BiocParallel namespace but not attached to the search path, so not accessible to 'users'. On the other hand the cost of attaching it (via `library()`) is minimal since it's already loaded.

Also, it might be better programming practice to `futile.logger::flog.debug(v)` so that nothing unnecessary ends up on the `search()` path.

**Comment by mtmorgan** [comment]
Also, you mentioned that you are writing a package. The package NAMESPACE is serailized to the worker, so that either of `fun1()` or `fun2()` would work

```
fun1 <- function()
    bplapply(1:10, function(v) flog.debug(v))

.fun <- function(v)
    flog.debug(v)

fun2 <- function()
    bplapply(1:10, .fun)
```

provided `flog.debug` has been imported into your package namespace (e.g., `importFrom(futile.logger, flog.debug)` in the NAMESPACE file).
