### ISSUE TITLE
package or namespace load failed for ‘BiocParallel’ in inDL

### ISSUE THREAD

**Issue by Lululuella** [Bioconductor/BiocParallel#90]
Hello,
I am writing a new bioconductor package with R 3.6 pre-release version.
R Under development (unstable) (2018-12-28 r75917) -- "Unsuffered Consequences"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Bioconductor is also devel veriosn: BiocManager::install(version = "devel")

I can install BiocParallel successfully by BiocManager::install("BiocParallel"). But I cannot load it:
> library(BiocParallel)
Error: package or namespace load failed for ‘BiocParallel’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object '~/R/win-library/3.6/BiocParallel/libs/x64/BiocParallel.dll':
  LoadLibrary failure:  A dynamic link library (DLL) initialization routine failed.

I also try to install package by BiocManager::install("BiocParallel",INSTALL_opts="--no-multiarch"). The issue is still the same.

I can use "BiocParallel" normally in R3.5.1. Could anyone help me on this?

**Comment by mtmorgan** [comment]
Does your BiocManager::install() command install from ' source' (downloading a file ending in .tar.gz) or binary (downloading a file ending in '.zip')? Does a dialog box or other indicate more detail about the DLL routine that fails?

**Comment by Lululuella** [comment]
Hi, I met weird thing when installing BiocManager. Maybe that is the reason. It is always said that BiocManager is out of date even after I agree to update it. There is no problem in a MAC.   BiocManager::valid() is TRUE and BiocParallel can be installed and loaded normally.

R Under development (unstable) (2018-12-28 r75917) -- "Unsuffered Consequences"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

> install.packages("BiocManager")
Installing package into ‘C:/Users/xxx/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/BiocManager_1.30.4.zip'
Content type 'application/zip' length 291894 bytes (285 KB)
downloaded 285 KB

package ‘BiocManager’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\xxx\AppData\Local\Temp\RtmpkfKtAO\downloaded_packages
> BiocManager::install(version = "devel")
Bioconductor version 3.9 (BiocManager 1.30.4), R Under development (unstable) (2018-12-28 r75917)
Installing package(s) 'BiocVersion'
trying URL 'https://bioconductor.org/packages/3.9/bioc/bin/windows/contrib/3.6/BiocVersion_3.9.0.zip'
Content type 'application/zip' length 8915 bytes
downloaded 8915 bytes

package ‘BiocVersion’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\xxx\AppData\Local\Temp\RtmpkfKtAO\downloaded_packages
Update old packages: 'BiocManager'
Update all/some/none? [a/s/n]: BiocManager::valid()      
Update all/some/none? [a/s/n]: 
n
> BiocManager::valid()    

* sessionInfo()

R Under development (unstable) (2018-12-28 r75917)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.4 compiler_3.6.0     tools_3.6.0       

Bioconductor version '3.9'

  * 1 packages out-of-date
  * 0 packages too new

create a valid installation with

  BiocManager::install("BiocManager", update = TRUE, ask = FALSE)

more details: BiocManager::valid()$too_new, BiocManager::valid()$out_of_date

Warning message:
1 packages out-of-date; 0 packages too new 
> if (!requireNamespace("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
> BiocManager::install("BiocParallel")
Bioconductor version 3.9 (BiocManager 1.30.4), R Under development (unstable) (2018-12-28 r75917)
Installing package(s) 'BiocParallel'
also installing the dependencies ‘formatR’, ‘lambda.r’, ‘futile.options’, ‘futile.logger’, ‘snow’, ‘BH’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/formatR_1.5.zip'
Content type 'application/zip' length 148843 bytes (145 KB)
downloaded 145 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/lambda.r_1.2.3.zip'
Content type 'application/zip' length 110808 bytes (108 KB)
downloaded 108 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/futile.options_1.0.1.zip'
Content type 'application/zip' length 20831 bytes (20 KB)
downloaded 20 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/futile.logger_1.4.3.zip'
Content type 'application/zip' length 102598 bytes (100 KB)
downloaded 100 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/snow_0.4-3.zip'
Content type 'application/zip' length 109648 bytes (107 KB)
downloaded 107 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/BH_1.66.0-1.zip'
Content type 'application/zip' length 17880032 bytes (17.1 MB)
downloaded 17.1 MB

trying URL 'https://bioconductor.org/packages/3.9/bioc/bin/windows/contrib/3.6/BiocParallel_1.17.3.zip'
Content type 'application/zip' length 1633646 bytes (1.6 MB)
downloaded 1.6 MB

package ‘formatR’ successfully unpacked and MD5 sums checked
package ‘lambda.r’ successfully unpacked and MD5 sums checked
package ‘futile.options’ successfully unpacked and MD5 sums checked
package ‘futile.logger’ successfully unpacked and MD5 sums checked
package ‘snow’ successfully unpacked and MD5 sums checked
package ‘BH’ successfully unpacked and MD5 sums checked
package ‘BiocParallel’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\xxx\AppData\Local\Temp\RtmpkfKtAO\downloaded_packages
Update old packages: 'BH', 'BiocManager', 'formatR', 'futile.logger', 'futile.options', 'lambda.r', 'snow'
Update all/some/none? [a/s/n]: 
n
> library(BiocParallel)
Error: package or namespace load failed for ‘BiocParallel’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/xxx/Documents/R/win-library/3.6/BiocParallel/libs/x64/BiocParallel.dll':
  LoadLibrary failure:  A dynamic link library (DLL) initialization routine failed.
>

**Comment by mtmorgan** [comment]
out of date even after updating is usually a symptom of the package being installed in two locations, usually one of the locations cannot be updated (e.g., owned by the system administrator). Check out `.libPaths()` and `installed.packages()` to diagnose further, with the typical solution being removal of the package from the non-writeable location.

**Comment by Lululuella** [comment]
I have set a user's lib path as the default. All packages will automatically installed under user's lib path.
> .libPaths()
[1] "C:/Users/xxx/Documents/R/win-library/3.6"
[2] "C:/Program Files/R/R-devel/library"            
 I check the documents under the two above folders. BiocManager folder only appear in the first default path.

I also try to install BiocManager in another windows computer with privilege of system administrator. No matter which path to install, the out-of-date problem is there.

**Comment by mtmorgan** [comment]
Is BiocManager already in use by another R session? Can you quit all sessions of R, then remove the BiocManager directory at C:/Users/xxx/Documents/R/win-library/3.6/BiocManager by hand and try again to install it?

**Comment by Lululuella** [comment]
I reinstalled R-devel, BiocManager and BiocParallel. Out-of-date problem is still there, but now library(BiocParallel) can work. Thanks!
