### ISSUE TITLE
 DelayedArray fails to build on several uncommon architecture

### ISSUE THREAD

**Issue by daissi** [Bioconductor/BiocParallel#91]
Hi,
 DelayedArray fails to build on several uncommon architectures ([at least on alpha, hurd, riscv64, sparc64](https://buildd.debian.org/status/package.php?p=r-bioc-delayedarray)) available in Debian:
```
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for 'DelayedArray':
 .onLoad failed in loadNamespace() for 'DelayedArray', details:
  call: if (length(workers) != 1L || workers < 0) msg <- c(msg, "'workers' must be integer(1) and >= 0")
  error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed
```
It fails when importing BiocParallel package and the failing code seems to be in [BiocParallel](https://github.com/Bioconductor/BiocParallel/blob/master/R/BiocParallelParam-class.R#L65-L66). So maybe, this bug can be forwarded to BiocParallel but as it appeared in DelayedArray, let start to speak here first.

 It looks like a misuse of detectCores() which can return a NA in some weird architectures but not correctly managed (similar bug appear in [NMF](https://bugs.debian.org/879248)).

Best,
Dylan

**Comment by mtmorgan** [comment]
Moved here where the issues occurs; thanks for the report Dylan.
