### ISSUE TITLE
Crash on bpstop

### ISSUE THREAD

**Issue by kjohnsen** [Bioconductor/BiocParallel#99]
I've run into an error using v1.17.18 that I didn't see on 1.16.6.  I had been running into problems in my package with `MulticoreParam()` if I didn't include `bpstop(bpparam())`. I get this:
```
Error in min(width(which), bpworkers(BPPARAM)) :
  invalid 'type' (list) of argument
```

But once I use `bpstop(bpparam())` it's fixed. The problem is, though, that that `bpstop()` line then crashes if I switch to `SerialParam()`. Here's an example (doesn't show the MulticoreParam problem, though):

```
library(BiocParallel)

bpp <- SerialParam()

x <- c(1, 2, 3)
addOne <- function(a, b) a+1
bplapply(x, addOne)

bpstop(bpp)
```

```
Error in if (cuid %in% names(env)) rm(list = cuid, envir = env) :
  argument is of length zero
```

Why is this? It seems I have to tweak things to get my package to work with a specific kind of param.

**Comment by mtmorgan** [comment]
Can you tell me how to reproduced the original problem?

**Comment by mtmorgan** [comment]
The problem with your code above is that you use `bpstop()` without first using `bpstart()`; I have made BiocParallel robust to this use in version 1.17.19.

I guess the original problem was from https://github.com/kjohnsen/MMAPPR2/blob/master/R/main.R#L1-L9. Remember that R is case sensitive, so the function argument `BPPARAM = NULL` is ignored other than in the test on line 3, so
```
> res = .runFunctionInParallel(1:4, identity, BPPARAM = BiocParallel::MulticoreParam())
Error in .runFunctionInParallel(1:4, identity, BPPARAM = BiocParallel::MulticoreParam()) :
  object 'bpParam' not found
```
Also, `bplapply()` respects the `bpisup()` state of the param it is presented with, so it is not necessary to explicitly call `bpstop()` -- as written and when no `BPPARAM=` argument is provided, `bpParam` is started / stopped within `bplapply()`. Also, BiocParallelParam classes are reference classes, so any change you make inside your function should be reverted before returning to your user; `on.exit()` is one way to do this.

I would instead implement your function as

```
.runFunctionInParallel <- function(inputList, functionToRun,
                                   ..., BPPARAM=bpparam()) {
    bppb_status = bpprogressbar(BPPARAM)
    on.exit({
        bpprogressbar(BPPARAM) <- bppb_status
    })
    bplapply(inputList, functionToRun, ..., BPPARAM=BPPARAM)
}
```

**Comment by kjohnsen** [comment]
Ok, thank you very much. I don't remember exactly why I added in the `bpstop()`, so I'll follow your suggestions and try and nail down the problem that resulted without it.
